export const FETCH_LIBROS_REQUEST = 'FETCH_LIBROS_REQUEST';
export const FETCH_LIBROS_SUCCESS = 'FETCH_LIBROS_SUCCESS';
export const FETCH_LIBROS_ERROR = 'FETCH_LIBROS_ERROR';

export const FETCH_LIBRO_REQUEST = 'FETCH_LIBRO_REQUEST';
export const FETCH_LIBRO_SUCCESS = 'FETCH_LIBRO_SUCCESS';
export const FETCH_LIBRO_ERROR = 'FETCH_LIBRO_ERROR';

export const ADD_LIBRO_REQUEST = 'ADD_LIBRO_REQUEST';
export const ADD_LIBRO_SUCCESS = 'ADD_LIBRO_SUCCESS';
export const ADD_LIBRO_ERROR = 'ADD_LIBRO_ERROR';

export const DELETE_LIBRO_REQUEST = 'DELETE_LIBRO_REQUEST';
export const DELETE_LIBRO_SUCCESS = 'DELETE_LIBRO_SUCCESS';
export const DELETE_LIBRO_ERROR = 'DELETE_LIBRO_ERROR';

export const UPDATE_LIBRO_REQUEST = 'UPDATE_LIBRO_REQUEST';
export const UPDATE_LIBRO_SUCCESS = 'UPDATE_LIBRO_SUCCESS';
export const UPDATE_LIBRO_ERROR = 'UPDATE_LIBRO_ERROR';
